AllCops:
  EnabledByDefault: true
  Exclude:
    - db/schema.rb
    - lib/tasks/cucumber.rake
    - script/cucumber
    - test/test_helper.rb
    - vendor/bundle/**/*

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100
  Exclude:
    - Gemfile
    - config/routes.rb

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false
